version: "3.8"

services:
  api:
    build: ./api
    container_name: flask_api
    ports:
      - "5001:5001"
    volumes:
      - ./scripts:/srv/scripts
    networks:
      - rnet
    environment:
      - FLASK_ENV=production
    restart: unless-stopped  # Ensure the container restarts automatically
  
  rserve:
    build: ./rserve
    container_name: rserve
    volumes:
      - ./scripts:/srv/scripts
      - ./rserve/Rserv.conf:/etc/Rserv.conf 
    ports:
      - "6311:6311"
    networks:
      - rnet
    environment:
      - R_ENVIRON=production
    restart: unless-stopped  # Ensure the container restarts automatically

  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    ports:
      - "8080:8080"  # Zeppelin web UI
      - "8443:8443"  # Optional SSL
    volumes:
      - zeppelin_data:/zeppelin
    networks:
      - rnet
    environment:
      - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_PORT=8080
    restart: unless-stopped  # Ensure the container restarts automatically

  rstudio:
    container_name: rstudio
    restart: unless-stopped  # Ensure the container restarts automatically
    build: ./rstudio
    volumes: 
      - ./rstudio/scripts_example:/home/rstudio/example_scripts
      - ./rstudio/projects:/home/rstudio/projects
    environment:
      - TZ=America/New_York
      - PASSWORD=password
    ports:
      - "8888:8787"
    networks:
      - rnet

volumes:
  zeppelin_data:

networks:
  rnet:
    driver: bridge
    name: rnet
