version: "3.8"

services:
  api:
    build: ./api
    container_name: flask_api
    ports:
      - "5001:5001"
    volumes:
      - ./scripts:/srv/scripts
    networks:
      - rnet
    environment:
      - FLASK_ENV=production
    restart: unless-stopped

  rserve:
    build: ./rserve
    container_name: rserve
    volumes:
      - ./scripts:/srv/scripts
      - ./rserve/Rserv.conf:/etc/Rserv.conf
    ports:
      - "6311:6311"
    networks:
      - rnet
    environment:
      - R_ENVIRON=production
    restart: unless-stopped

  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: zeppelin
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - zeppelin_data:/zeppelin
    networks:
      - rnet
    environment:
      - ZEPPELIN_ADDR=0.0.0.0
      - ZEPPELIN_PORT=8080
    restart: unless-stopped

  rstudio:
    container_name: rstudio
    restart: unless-stopped
    build: ./rstudio
    volumes: 
      - ./rstudio/scripts_example:/home/rstudio/example_scripts
      - ./rstudio/projects:/home/rstudio/projects
    environment:
      - TZ=America/New_York
      - PASSWORD=password
    ports:
      - "8888:8787"
    networks:
      - rnet

  jupyterhub:
    container_name: jupyterhub
    build: ./jupyterhub
    volumes:
      - ./jupyterhub:/srv/jupyterhub
    ports:
      - "8000:8000"
    networks:
      - rnet
    environment:
      - JUPYTERHUB_CONFIG=/srv/jupyterhub/jupyterhub_config.py
    restart: unless-stopped



volumes:
  zeppelin_data:
  jupyterhub_data:

networks:
  rnet:
    driver: bridge
    name: rnet
